version: "3.2"
services:
  db:
    image: neo4j:latest
    container_name: "ancestree-db"
    volumes:
      - "./database/data:/data"
      - "./database/conf/:/conf/"
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
    environment:
      - NEO4J_AUTH=neo4j/s3cr3t
    networks:
      - neo4j_go_net
    command: neo4j
  api:
    container_name: "ancestree-api"
    build: "./api"
    ports:
      - "8080:8080"
    restart: "always"
    volumes:
      - "./api:/go/src/app"
    depends_on:
      - "db"
    networks:
      - neo4j_go_net

networks:
  neo4j_go_net:
    driver: bridge