# [[tls.certificates]] #first certificate
#    certFile = "/traefik/letsencrypt/procopius.localhost.crt"
#    keyFile = "/traefik/letsencrypt/procopius.localhost.key"

# [tls.stores]
#   [tls.stores.default]
#     [tls.stores.default.defaultCertificate]
#       certFile = "/traefik/letsencrypt/procopius.localhost.crt"
#       keyFile  = "/traefik/letsencrypt/procopius.localhost.key"